# Generated by Django 4.0 on 2023-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.CharField(max_length=100)),
                ('P', models.CharField(max_length=100)),
                ('K', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('rainfall', models.CharField(max_length=100)),
            ],
        ),
    ]
